### ISSUE TITLE
[Error 1106] On using the correct credentials and phone number

### ISSUE THREAD

**Issue by kirit1193** [tuya/tuya-homebridge#110]
I'm unable to login to my account using either my email ID or registered phone number via HomeBridge running latest version of the official plugin.

```
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyacn.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":91,"username":"<username>","password":"<pwd>","schema":"tuyaSmart"}, headers = {"t":"1632066113715","client_id":"<client-id>","nonce":"1cfa4000-1960-11ec-9f0d-ff89b2bc10de","Signature-Headers":"client_id","sign":"71C5A44C959A8065B0C54452EEDD83F4F951BBD603FB45B40022E180B85AB610","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.4.0"}
Starting to advertise 'TuyaPlatform 9239' using bonjour-hap backend!
[9/19/2021, 9:11:53 PM] Homebridge v1.3.4 (TuyaPlatform) is running on port 36487.
TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1632066114937} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
```

Getting 1106 even when I use my phone number instead of email address.

**Comment by kirit1193** [comment]
Update, the issue persists even on changing the endpoint manually to my region.

Request:

`TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyain.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":91,"username":"<phone>","password":"<pw>","schema":"tuyaSmart"}, headers = {"t":"1632479364341","client_id":"gc9dknqnaqxjxbnlk0gs","nonce":"499cf740-1d22-11ec-984d-a5763c32c80b","Signature-Headers":"client_id","sign":"0CE20076C6035DECDE080136ACB6A2A617520E1263E6147C53469007D008E4BF","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.4.1"}`

Response:

`TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1632479364547} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:48:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TuyaSHOpenAPI.request (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:144:7)
    at TuyaSHOpenAPI.getDevices (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:62:15)
    at TuyaPlatform.initTuyaSDK (/usr/lib/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.`

**Comment by kirit1193** [comment]
This issue was resolved by using the Tuya Smart app credentials instead of the IOT API credentials. Marking as closed.
