### ISSUE TITLE
Constantly getting the 2406 error code when setting it up

### ISSUE THREAD

**Issue by Jacko539** [tuya/tuya-homebridge#142]
I just can’t seem to get this set up. I have followed the steps and created a cloud project and I have linked this to my Smart Life app and can see my devices showing up on the website but I just can’t get them to show in Homebridge

hope the info below helps. Thanks

TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":xxxxxx} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (C:\Users\\AppData\Roaming\npm\node_modules\homebridge-tuya-platform\lib\tuyashopenapi.js:48:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at TuyaSHOpenAPI.request (C:\Users\\AppData\Roaming\npm\node_modules\homebridge-tuya-platform\lib\tuyashopenapi.js:144:7)
    at TuyaSHOpenAPI.getDevices (C:\Users\\AppData\Roaming\npm\node_modules\homebridge-tuya-platform\lib\tuyashopenapi.js:62:15)
    at TuyaPlatform.initTuyaSDK (C:\Users\\AppData\Roaming\npm\node_modules\homebridge-tuya-platform\index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!

       {
            "options": {
                "username": "xxxx",
                "password": "xxxxx",
                "accessId": "",
                "accessKey": "xxxx",
                "lang": "en",
                "endpoint": "https://openapi.tuyaeu.com",
                "projectType": "2",
                "appSchema": "smartlife",
                "countryCode": 44,
                "debug": true
            },
            "name": "TuyaPlatform",
            "platform": "TuyaPlatform"
        }

**Comment by Hanh94** [comment]
Please see https://github.com/tuya/tuya-homebridge/issues/134#issuecomment-957266378
