### ISSUE TITLE
unable to add devices to HomeKit getting error 2406

### ISSUE THREAD

**Issue by balajikhandekar** [tuya/tuya-homebridge#143]
Hello,

I am getting following error while adding tuya plugin to homebridge.
I read somewhere in documentation that project should be created after may 25, 2021 and it should be paas.
My project is created today(31 Oct 2021) and its with Paas as stated in documentation.

Any pointers what's going on wrong here?
-----
Error below

TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:48:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TuyaSHOpenAPI.request (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:144:7)
    at TuyaSHOpenAPI.getDevices (/usr/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:62:15)
    at TuyaPlatform.initTuyaSDK (/usr/lib/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!

**Comment by polmv123** [comment]
@balajikhandekar  https://github.com/tuya/tuya-homebridge/issues/144

**Comment by Hanh94** [comment]
Please see https://github.com/tuya/tuya-homebridge/issues/134#issuecomment-957266378

**Comment by balajikhandekar** [comment]
Thanks @polmv123 ,

changing url in tuya config worked like charm.
