### ISSUE TITLE
how to change endpoint from us to eu. 

### ISSUE THREAD

**Issue by Tomaholk1** [tuya/tuya-homebridge#144]
**Describe the bug**

I don't know how to change endpoint from us to eu. I do not have such a possibility in the configuration.

**Screenshots**
https://www47.zippyshare.com/v/fMCQYFYP/file.html

**Login request 

TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":1635701861691} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:48:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TuyaSHOpenAPI.request (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:144:7)
    at TuyaSHOpenAPI.getDevices (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:62:15)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.

**Comment by Tomaholk1** [comment]
ok.  i did it.

you should go to terminal and use:
sudo vi /usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js

next you should change :
//this.endpoint = (this.countryCode && this.countryCode == 86)? 'https://openapi.tuyacn.com' : 'https://openapi.tuyaus.com'

for this:
this.endpoint = 'https://openapi.tuyaeu.com';

to do that we use vi program. 
here you have more details: https://pl.wikipedia.org/wiki/Vi_(program)

**Comment by polmv123** [comment]
Still not working for me :(. Getting the same error

**Comment by polmv123** [comment]
That worked for me. Thanks mate.

**Comment by Hanh94** [comment]
Please see https://github.com/tuya/tuya-homebridge/issues/134#issuecomment-957266378
