### ISSUE TITLE
Error - 1109

### ISSUE THREAD

**Issue by xrust83** [tuya/tuya-homebridge#153]
TuyaOpenAPI response: {"code":1109,"msg":"param is illegal, please check it","success":false,"t":1636213979419} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:49:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TuyaSHOpenAPI.request (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:145:7)
    at TuyaSHOpenAPI.getDevices (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:63:15)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.
**request path = /v1.0/iot-01/associated-users/actions/authorized-login**

There are no error descriptions here
https://developer.tuya.com/en/docs/iot/error-code?id=K989ruxx88swc

**Comment by xrust83** [comment]
https://github.com/tuya/tuya-homebridge/issues/134#issuecomment-948002663

the solution helped me too as here

**Comment by leo150** [comment]
The solution didn't help me. I'm based in Canada, so the host was correct. What helped was:
* Create new account on IoT website, with region Canada
* Link mobile phone
* Create a new smart home project with both Western and Eastern America data centers
* Create new account for Tuya mobile app. Region Canada is auto selected and can't be changed. It was wrong when I user Google login.
* Reinstall tuya plugin because it caches config
