### ISSUE TITLE
Heatstorm Heater Error Temperature Display Units 

### ISSUE THREAD

**Issue by ShaunRoberts543** [tuya/tuya-homebridge#198]
Hello,
I am getting this error on my Heatstorm Heating device.  It appears to be working but in HomeKit it is showing me a tempature of 156 degrees F, which is obviously not accurate.

[11/01/2022, 20:28:49] [homebridge-tuya-platform] This plugin threw an error from the characteristic 'Temperature Display Units': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://git.io/JtMGR for more info.
[11/01/2022, 20:28:49] [homebridge-tuya-platform] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at TemperatureDisplayUnits.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/heater_accessory.js:114:11)
    at TemperatureDisplayUnits.emit (node:events:402:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1544:14
    at new Promise (<anonymous>)
    at TemperatureDisplayUnits.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1542:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)

**Comment by sdaltons1** [comment]
I'm pretty sure your heater is locked into celsius.  I have an atomi heater set up through this plug-in and it shows 153 degrees, but if you go into the settings and look at the "unit" option, it shows it's displaying celsius.  It looks like it is going to let you switch it to fahrenheit, but then you can't actually click it.  Hope this helps in resolving the issue.

**Comment by ShaunRoberts543** [comment]
I’m glad you mentioned Atomi. I was wondering if their products would work with Tuya or not.

**Comment by sdaltons1** [comment]
Atomi does work and I was pretty pumped when I figured it out lol. 

Really wish there was a database somewhere, especially since so many different smart apps look and feel very similar to Tuya/Smart Life. Just a list of brands that work with Tuya would be huge.

**Comment by sjafferali** [comment]
This looks really similar https://github.com/home-assistant/homebridge-homeassistant/issues/222

**Comment by WeekendSuperhero** [comment]
I think the enum types need to start at 1 instead of 0 and the error should go away

**Comment by huggi001** [comment]
> I'm pretty sure your heater is locked into celsius. I have an atomi heater set up through this plug-in and it shows 153 degrees, but if you go into the settings and look at the "unit" option, it shows it's displaying celsius. It looks like it is going to let you switch it to fahrenheit, but then you can't actually click it. Hope this helps in resolving the issue.

Yeah, I've got three Atomi heaters and have noticed the same thing.  Also noticed when I click on Fahrenheit, it won't select and the check mark stays on Celsius but then the heater gives a "No Response" back.  Clicking on Celsius again and the heater is back online.

**Comment by randymwill** [comment]
I'm also having the same issue with 2 Heat Storm devices. Any updates?

**Comment by colton123e** [comment]
Any updates on this issue? I'm still seeing the same issue mentioned here on an Atomi tower heater.

**Comment by enz1ey** [comment]
I have the same issue with the Heat Storm wall heater. The heater itself can be configured to show either C or F, but in HomeKit, it only shows C.

**Comment by BMWAdriano** [comment]
Still an issue. Is there any hope for this?
