### ISSUE TITLE
Can't get linked devices

### ISSUE THREAD

**Issue by maaper** [tuya/tuya-homebridge#244]
### **Describe the bug**

I follow all steps to log in and config the plugin properly.
The plugin seem to be running ok (green light on the plugin dashboard)
However, no devices are show on devices list.
I just turn on the debug option and see this on the log.

```
[5/21/2022, 1:56:06 PM] Homebridge v1.4.1 (HAP v0.10.2) (Camera FFmpeg) is running on port 57799.
TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1653134166387,"tid":"ff04acebd8fc11eca733f2b4cd1fee5a"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:49:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TuyaSHOpenAPI.request (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:145:7)
    at TuyaSHOpenAPI.getDevices (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:63:15)
    at TuyaPlatform.initTuyaSDK (/homebridge/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.
```

Honestly I don't know what to do next in order to solve the issue.

### **Login request**

Initializing TuyaPlatform...
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":34,"username":"XXXXXXXXXXXX","password":"XXXXXXXXXXXX","schema":"smartlife"}, headers = {"t":"1653134166154","client_id":"tcewp4kg3ymateucxyaw","nonce":"fecba580-d8fc-11ec-ada5-3157887dbdf9","Signature-Headers":"client_id","sign":"BF6101589088F53BAD9CEC080EADEFD0A2DA87133F7FB01E7FD97030D66B3F4A","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}

Thanks in advance for the support.

**Comment by UnlikelyDuck** [comment]
I have exactly this problem as well, including the debug log details as above.
