### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by vahov** [tuya/tuya-homebridge#30]
I get this warning and no devices are showing up. Please help:

(node:17584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at TuyaSHOpenAPI.getDevices (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:69:78)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:80:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Config file:

"options": {
                "username": "iii.jjjj@icloud.com",
                "password": "XXXX",
                "accessId": "cgctdtgxxxxxx",
                "accessKey": "hjgjffffffff",
                "lang": "en",
                "projectType": "2",
                "appSchema": "smartlife",
                "endPoint": "https://openapi.tuyaeu.com",
                "countryCode": 372,
                "debug": false
            },
            "name": "TuyaPlatform",
            "platform": "TuyaPlatform"

**Comment by Hanh94** [comment]
Hi @vahov ,We have received your problem.
Please check the log to see if the device_ids parameter for the corresponding request is null and if the response is null, like this:
```TuyaOpenAPI request: method = get, endpoint = https://openapi.tuyacn.com, path = /v1.0/devices/functions, params = {"device_ids":"6cb2c761afc1e455d3rakk,vdevo162282170700731,vdevo162253000699035,vdevo162244768354769,12228800840d8e62ef5a,vdevo162046895384614,vdevo162045745277206,6cc955cba6bf32414ed3ap,vdevo162203611053951,vdevo162202787804733,vdevo162202667091084,vdevo162202263518228,vdevo162202171518573,vdevo162202050388321,vdevo162202004354402,vdevo162063248244372,vdevo162061520113379,vdevo162046602404102,vdevo162046568441625,vdevo162045764205721"}, body = null, headers = {"t":"1623035331399","client_id":"xxx","sign":"xxx","sign_method":"HMAC-SHA256","access_token":"xxx","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.0.6"}```

```
TuyaOpenAPI response: {"result":[{"category":"fs","devices":["6cb2c761afc1e455d3rakk"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"fan_speed_percent","desc":"fan speed percent","name":"fan speed percent","type":"Integer","values":"{\"min\":\"1\",\"max\":\"12\",\"scale\":\"0\",\"step\":\"1\"}"}],"product_id":"ybznohgystymcfpt"},{"category":"kj","devices":["12228800840d8e62ef5a"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"speed","desc":"speed","name":"speed","type":"Enum","values":"{\"range\":[\"1\",\"2\",\"3\"]}"},{"code":"filter_reset","desc":"filter reset","name":"filter reset","type":"Boolean","values":"{}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Enum","values":"{\"range\":[\"1\",\"2\"]}"}],"product_id":"xbwu1pxknjob6ca7"},{"category":"cl","devices":["vdevo162202171518573"],"functions":[{"code":"control","desc":"control","name":"control","type":"Enum","values":"{\"range\":[\"open\",\"stop\",\"close\",\"continue\"]}"},{"code":"percent_control","desc":"percent control","name":"percent control","type":"Integer","values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"},{"code":"mode","desc":"mode","name":"mode","type":"Enum","values":"{\"range\":[\"morning\",\"night\"]}"},{"code":"control_back_mode","desc":"control back mode","name":"control back mode","type":"Enum","values":"{\"range\":[\"forward\",\"back\"]}"},{"code":"auto_power","desc":"auto power","name":"auto power","type":"Boolean","values":"{}"},{"code":"countdown_set","desc":"countdown set","name":"countdown set","type":"Enum","values":"{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\"]}"},{"code":"border","desc":"border","name":"border","type":"Enum","values":"{\"range\":[\"up\",\"down\",\"up_delete\",\"down_delete\",\"remove_top_bottom\"]}"},{"code":"position_best","desc":"position best","name":"position best","type":"Integer","values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"},{"code":"click_control","desc":"click control","name":"click control","type":"Enum","values":"{\"range\":[\"up\",\"down\"]}"},{"code":"angle_horizontal","desc":"angle horizontal","name":"angle horizontal","type":"Integer","values":"{\"min\":0,\"max\":180,\"scale\":0,\"step\":1}"}],"product_id":"lhcosaeuwqlcf5kw"},{"category":"cz","devices":["vdevo162244768354769"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"obqigmfjfjegilqh"},{"category":"kg","devices":["vdevo162202263518228"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"bpkf4jdsuxhnmlg3"},{"category":"cs","devices":["vdevo162046568441625"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"dehumidify_set_value","desc":"dehumidify set value","name":"dehumidify set value","type":"Integer","values":"{\"unit\":\"%\",\"min\":35,\"max\":80,\"scale\":0,\"step\":5}"},{"code":"fan_speed_enum","desc":"fan speed enum","name":"fan speed enum","type":"Enum","values":"{\"range\":[\"low\",\"mid\",\"high\"]}"},{"code":"mode","desc":"mode","name":"mode","type":"Enum","values":"{\"range\":[\"dehumidify\",\"drying\",\"continuous\"]}"}],"product_id":"sywzmo5jnnvzxemn"},{"category":"kg","devices":["vdevo162202667091084"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"sk4h2itvu5nhvvns"},{"category":"fskg","devices":["vdevo162202004354402"],"functions":[{"code":"switch_fan","desc":"switch fan","name":"switch fan","type":"Boolean","values":"{}"}],"product_id":"mvvkvj9gclwpgaol"},{"category":"dj","devices":["vdevo162282170700731"],"functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"},{"code":"bright_value_v2","desc":"bright value v2","name":"bright value v2","type":"Integer","values":"{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"temp_value_v2","desc":"temp value v2","name":"temp value v2","type":"Integer","values":"{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"},{"code":"scene_data_v2","desc":"scene data v2","name":"scene data v2","type":"Json","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"cawmqr8i"},{"category":"kg","devices":["vdevo162253000699035"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"switch_2","desc":"switch 2","name":"switch 2","type":"Boolean","values":"{}"},{"code":"switch_3","desc":"switch 3","name":"switch 3","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"countdown_2","desc":"countdown 2","name":"countdown 2","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"countdown_3","desc":"countdown 3","name":"countdown 3","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"fmwg7tnoyaydxujr"},{"category":"cz","devices":["vdevo162202050388321"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"relay_status","desc":"relay status","name":"relay status","type":"Enum","values":"{\"range\":[\"power_off\",\"power_on\",\"last\"]}"},{"code":"light_mode","desc":"light mode","name":"light mode","type":"Enum","values":"{\"range\":[\"relay\",\"pos\",\"none\"]}"},{"code":"child_lock","desc":"child lock","name":"child lock","type":"Boolean","values":"{}"}],"product_id":"vljzxg8omklkco9n"},{"category":"ckmkzq","devices":["vdevo162046602404102"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"tr_timecon","desc":"tr timecon","name":"tr timecon","type":"Integer","values":"{\"unit\":\"s\",\"min\":10,\"max\":120,\"scale\":0,\"step\":1}"},{"code":"countdown_alarm","desc":"countdown alarm","name":"countdown alarm","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"8jhmw9dvd92qjvm0"},{"category":"dj","devices":["vdevo162046895384614"],"functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"},{"code":"bright_value_v2","desc":"bright value v2","name":"bright value v2","type":"Integer","values":"{\"min\":10,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}"},{"code":"temp_value_v2","desc":"temp value v2","name":"temp value v2","type":"Integer","values":"{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}"},{"code":"colour_data_v2","desc":"colour data v2","name":"colour data v2","type":"Json","values":"{}"},{"code":"scene_data_v2","desc":"scene data v2","name":"scene data v2","type":"Json","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"control_data","desc":"control data","name":"control data","type":"Json","values":"{}"}],"product_id":"yju2e6dooxujr5zx"},{"category":"dj","devices":["vdevo162045764205721"],"functions":[{"code":"switch_led","desc":"switch led","name":"switch led","type":"Boolean","values":"{}"},{"code":"flash_scene_1","desc":"flash scene 1","name":"flash scene 1","type":"Json","values":"{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"},{"code":"flash_scene_2","desc":"flash scene 2","name":"flash scene 2","type":"Json","values":"{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"},{"code":"flash_scene_3","desc":"flash scene 3","name":"flash scene 3","type":"Json","values":"{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"},{"code":"work_mode","desc":"work mode","name":"work mode","type":"Enum","values":"{\"range\":[\"colour\"]}"},{"code":"bright_value","desc":"bright value","name":"bright value","type":"Integer","values":"{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"},{"code":"colour_data","desc":"colour data","name":"colour data","type":"Json","values":"{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"},{"code":"scene_data","desc":"scene data","name":"scene data","type":"Json","values":"{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"},{"code":"flash_scene_4","desc":"flash scene 4","name":"flash scene 4","type":"Json","values":"{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"}],"product_id":"iDdXdkIr84vFcAgA"},{"category":"cz","devices":["vdevo162045745277206"],"functions":[{"code":"switch_1","desc":"switch 1","name":"switch 1","type":"Boolean","values":"{}"},{"code":"countdown_1","desc":"countdown 1","name":"countdown 1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"product_id":"4vyFlNarPqM5IofI"}],"success":true,"t":1623035332140} path = /v1.0/devices/functions
```

**Comment by Hanh94** [comment]
Hi @vahov ,Thank you for your feedback.
We have fixed this issue in the latest version, please update and try again.

**Comment by vahov** [comment]
Thank you, it is indeed fixed. 
Now there is one question - I have two homes and two Smartlife accounts with different login credentials. I added this plugin only to one home so far, filled the required fields with this home data but Homebridge loaded all the other homes accessories as well. I have one project with devices from two different app accounts, is it maybe so, that I have to create two different projects?

**Comment by Hanh94** [comment]
Hi @vahov , If you want to use them at the same time and want to pull devices under different accounts separately, it can only be to create different projects. If you do not use two accounts at the same time, you can use one project to connect and bind Tuya accounts in turn.

**Comment by vahov** [comment]
Ok, thank you
