### ISSUE TITLE
TuyaOpenAPI response: {"code":1106,"msg":"permission deny"

### ISSUE THREAD

**Issue by wrmacj** [tuya/tuya-homebridge#309]
**Describe the bug**
New devices are not added.  They show up in Smart Life and on the Tuya IoT Platform.  When I turned on Debug mode I seen the following error.
After uninstalling the Tuya plugin and reinstalling it no longer adds any devices.

Thank you for any assistance.

Initializing TuyaPlatform...
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaus.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":1,"username":"wrmacj@outlook.com","password":"91d9724498318b07aa4c48eeb0d4bee0","schema":"smartlife"}, headers = {"t":"1666220994913","client_id":"7facv9y9wnhgtcfu8qrf","nonce":"24a4af91-5003-11ed-8c9b-25b59857685a","Signature-Headers":"client_id","sign":"D70EFF696B52404977362F72334810301ABEAC439A2A04ADFAFC56FAE519E39B","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
[10/19/2022, 7:09:54 PM] Homebridge v1.5.0 (HAP v0.10.2) (TuyaPlatform) is running on port 35360.
TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1666220995329,"tid":"24e982cb500311eda5021297425bcc23"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:49:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TuyaSHOpenAPI.request (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:145:7)
    at TuyaSHOpenAPI.getDevices (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:63:15)
    at TuyaPlatform.initTuyaSDK (/homebridge/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.

            "options": {
                "username": "xxxxx@outlook.com",
                "password": "xxxxxxxxxxxxxxxxxxxx",
                "accessId": "xxxxx",
                "accessKey": "xxxxx",
                "lang": "en",
                "projectType": "2",
                "appSchema": "smartlife",
                "countryCode": 1,
                "debug": true
            },
            "name": "TuyaPlatform",
            "_bridge": {
                "username": "xxxxx",
                "port": 35360
            },
            "platform": "TuyaPlatform"

**Comment by wrmacj** [comment]
If I restore a config from last week this is the debug.  The think is that I do not know if I had a problem at this time.  I have reset my

**Comment by wrmacj** [comment]
I had updated my Smart Life password.  I had mistakenly been using my Tuya password....Who knew :)  Arrrg....
Sorry.
