### ISSUE TITLE
the plugin does not work

### ISSUE THREAD

**Issue by federicodigiacomo** [tuya/tuya-homebridge#315]
for 2 days that in the homebridge log I find:

`TuyaOpenAPI response: {"code":1013,"msg":"request time is invalid","success":false,"t":1667155742759,"tid":"85d303f8588311ed8a08fe1b67a66e75"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:49:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TuyaSHOpenAPI.request (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:145:7)
    at TuyaSHOpenAPI.getDevices (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:63:15)
    at TuyaPlatform.initTuyaSDK (/homebridge/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.`

I can no longer command devices, please help me

**Comment by federicodigiacomo** [comment]
Anyone?

**Comment by federicodigiacomo** [comment]
Solved, the time was not synchronised
