### ISSUE TITLE
Error 2406

### ISSUE THREAD

**Issue by jormajo** [tuya/tuya-homebridge#391]
**Describe the bug**
I can no longer login into Tuya IOT Developer platform

** Log file **
[6/6/2024, 3:30:20 PM] [HB Supervisor] Restarting Homebridge...
[6/6/2024, 3:30:20 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules -D -K --strict-plugin-resolution
[6/6/2024, 3:30:20 PM] [HB Supervisor] Started Homebridge v1.8.2 with PID: 2693
[6/6/2024, 3:30:23 PM] Loaded config.json with 0 accessories and 2 platforms.
[6/6/2024, 3:30:23 PM] Loaded 0 cached accessories from cachedAccessories.
[6/6/2024, 3:30:23 PM] ---
[6/6/2024, 3:30:24 PM] Loaded plugin: homebridge-tuya-platform@1.5.0
[6/6/2024, 3:30:24 PM] Registering platform 'homebridge-tuya-platform.TuyaPlatform'
[6/6/2024, 3:30:24 PM] ---
[6/6/2024, 3:30:24 PM] Loading 2 platforms...
[6/6/2024, 3:30:24 PM] [TuyaPlatform] Initializing TuyaPlatform platform...
Initializing TuyaPlatform...
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-01/associated-users/actions/authorized-login, params = null, body = {"country_code":34,"username":"jordi@majo.cat","password":"3e965ef0c2b3e76ef43fa3bd9217b18a","schema":"smartlife"}, headers = {"t":"1717680624340","client_id":"gjap3nvs4vpyggjm8eya","nonce":"edc69ed0-2408-11ef-82f7-67fd0d838289","Signature-Headers":"client_id","sign":"97AC9378BC4100D43B9AAF5A4C549F008B868EFB7BB6E01EA9DE193A2149415F","sign_method":"HMAC-SHA256","access_token":"","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.5.0"}
[6/6/2024, 3:30:25 PM] Publishing bridge accessory (name: Homebridge 2AE5, publishInfo: {
  username: '0E:31:0C:6D:2A:E5',
  port: 51740,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
Setup Payload:
X-HM://0024Z10M9O0BN
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxx-xx-xxx │     
    └────────────┘     
                       
[6/6/2024, 3:30:25 PM] Homebridge v1.8.2 (HAP v0.12.1) (Homebridge 2AE5) is running on port 51740.
TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":1717680625389,"tid":"ee9cfc52240811efbe221ede1b7ee1c1"} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:49:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TuyaSHOpenAPI.request (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:145:7)
    at TuyaSHOpenAPI.getDevices (/homebridge/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:63:15)
    at TuyaPlatform.initTuyaSDK (/homebridge/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.

Any help will be greatly appreciated

**Comment by sakuradon99** [comment]
same issue
