### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by okilic93** [tuya/tuya-homebridge#62]
Hi , I am getting below error on the HomeBridge panel after I ınstalled.

Do you have any idea regarding this error ?

Thank you in `advance.`

`(node:4376) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 76caae69-66bf-4778-b609-da43e9c0a1ab
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:593:12)
    at BridgeService.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:382:17)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:340:10)
    at TuyaPlatform.registerPlatformAccessory (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:199:14)
    at new BaseAccessory (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/base_accessory.js:50:21)
    at new SwitchAccessory (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/switch_accessory.js:11:5)
    at TuyaPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:139:27)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:96:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Hanh94** [comment]
Hi @okilic93 , sorry for the late reply.
This is a known question of HomeBridge, perhaps the answer [here](https://github.com/homebridge/homebridge/issues?q=is%3Aissue+is%3Aclosed+Cannot+add+a+bridged+Accessory+with+the+same+UUID+as+another+bridged+Accessory) can help you better, please refer to it.
